# Generated by Django 5.0.2 on 2024-04-13 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costureras',
            fields=[
                ('identificacion', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Fabrica',
            fields=[
                ('nit', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('id_costura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabrica.costureras')),
            ],
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('cant_prendas', models.IntegerField()),
                ('fecha_ini', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('id_costurera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fabrica.costureras')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabrica.estado')),
                ('id_fabrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabrica.fabrica')),
            ],
        ),
    ]
