# Generated by Django 5.0.2 on 2024-04-19 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabrica',
            name='costura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fabrica.costureras'),
        ),
    ]
