# Generated by Django 5.0.4 on 2024-04-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrica', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fabrica',
            old_name='id_costura',
            new_name='costura',
        ),
        migrations.RenameField(
            model_name='tareas',
            old_name='id_costurera',
            new_name='costurera',
        ),
        migrations.RenameField(
            model_name='tareas',
            old_name='id_estado',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='tareas',
            old_name='id_fabrica',
            new_name='fabrica',
        ),
        migrations.AlterField(
            model_name='estado',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
