# Generated by Django 5.0.4 on 2024-04-14 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabrica', '0002_rename_id_costura_fabrica_costura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estado',
            name='descripcion',
        ),
    ]
